### ISSUE TITLE
Is there any way to use this plugin in Godot 3.x ?

### ISSUE THREAD

**Issue by souvikinator** [appsinacup/godot-rapier-2d#37]
Hi there! Great plugin. Recently came across this however found that this only works for Godot 4.x
Is there a way I can use this for Godot 3.x (specifically Godot 3.5)

Thank you

**Comment by Ughuuu** [comment]
In order to use this, it needs to be a module in Godot 3.x, while right now it's a GDExtension. It needs some amount of work to make work, but I don't think it would be worth as much, as that would mean it won't be a GDExtension anymore. I wouldn't want a module, and also wouldn't want maintaining both. If anyone wants to take this in the future, you can comment here, tough I think it would be more important to make it work better.

So to answer your question, right now there isn't any way to use it as is for Godot 3.x

**Comment by souvikinator** [comment]
Got it. Thanks.

**Comment by Ughuuu** [comment]
Hm, actually looking at https://gitlab.com/snopek-games/sg-physics-2d I see they basically reimplemented how physics server works in godot 4, and make the whole implementation of their physics thing a helper. Might be a solution for the future, but definitely will require a lot of work.
