### ISSUE TITLE
Rapier2D doesn't work the same as Default with Physics Materials Godot 4.2.1 mono

### ISSUE THREAD

**Issue by GeminiSquishGames** [appsinacup/godot-rapier-2d#74]
The example project is: https://github.com/GeminiSquishGames/Rapier2Dbug

The box static collision has a physics material set for max bounce and friction, no absorb. The ball is a plain RBody. Switch between the two physics engines to see that Rapier behaves more erratically with the same settings as Godot's default which it should be set too when you open it. This is using Godot 4.2.1 mono,

Edit: Seems like rough-checked friction applies the wrong angular velocity, transfers to the opposite rotational velocity. Then it collects too much linear?

**Comment by GeminiSquishGames** [comment]
Ugh, sorry mans. I'm about ready to call it a day, lol. Okay, it's public now and yeah, as long as rough is on it seems to be the key factor. I just updated it with a firing body that should mostly mimic what I'm using.

**Comment by Ughuuu** [comment]
Ok, the problem here seems to be that in godot if rough is true, it sets friction negative. Hm. I'll see if I can replicate same behaviour as rough checkbox in rapier.

**Comment by Ughuuu** [comment]
Ok, it appears negative friction and bounce isn't supported for now, since rapier doesn't support it. I opened an issue to see if/how it will be solved: https://github.com/dimforge/rapier/issues/622

For now disabling the `absorbent` and `rough` checkboxes(they will simply do no-op) until the linked issue is fixed on rapier.
